#!/usr/bin/env python3

import rospy
from migrave_face_feature_detector_wrapper.face_feature_detector_wrapper import FaceFeatureDetectorWrapper

if __name__ == '__main__':
    rospy.init_node("face_feature_detector")
    rospy.loginfo("Face feature detector node is running...")
    face_feature_detector = FaceFeatureDetectorWrapper()

    try:
        while not rospy.is_shutdown():
            face_feature_detector.run()
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print("Person feature detector exiting...")
