#!/usr/bin/env python3

import rospy
from migrave_face_feature_detector_wrapper.nuitrack_face_feature_detector_wrapper import NuitrackFaceFeatureDetectorWrapper

if __name__ == '__main__':
    rospy.init_node("nuitrack_face_feature_detector")
    rospy.loginfo("Nuitrack face feature detector node is running...")
    nuitrack_face_feature_detector = NuitrackFaceFeatureDetectorWrapper()

    try:
        nuitrack_face_feature_detector.initialize()
        while not rospy.is_shutdown():
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print("Nuitrack face feature detector wrapper exiting...")
