#!/usr/bin/env python3
import rospy
from migrave_audio_feature_detector_wrapper.audio_feature_detector_wrapper import AudioFeatureDetectorWrapper

if __name__ == '__main__':
    rospy.init_node("audio_feature_detector")
    rospy.loginfo("Audio feature detector node is running...")
    audio_feature_detector = AudioFeatureDetectorWrapper()

    try:
        audio_feature_detector.run()
        while not rospy.is_shutdown():
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print("Audio feature detector exiting...")
