#!/usr/bin/env python3

import numpy as np

import rospy

from mas_tools.ros_utils import get_package_path
from action_recognition.action_classifier import ActionClassifier
from action_recognition.action_model import ActionModel

if __name__ == "__main__":
    rospy.init_node("action_recognizer_demo")

    model_cfg_file = get_package_path("migrave_action_recognition", "config", "action_model_config.yaml")
    action_list_file = get_package_path("migrave_action_recognition", "config", "action_list.txt")

    action_model = ActionModel(model_cfg_file, action_list_file)
    action_classifier = ActionClassifier(action_model)

    try:
        rospy.loginfo('Sleeping for 3 seconds; get into position!')
        rospy.sleep(3.)
        rospy.loginfo('Capturing data...')
        action_classifier.record = True
        while not rospy.is_shutdown():
            action = action_classifier.classify_action()
            if action is not None:
                rospy.loginfo('Recognized action: %s, index %d', action[0], action[1])
            rospy.sleep(3.)
    except (KeyboardInterrupt, SystemExit):
        print('action_recognizer_demo interrupted; exiting...')
