batch_size: 64
cperhead: 2
exemplars_name: exemplars_model11.pkl
heads:
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 1
model_args:
  lr: 0.1
  lr_factor: 0.1
  lr_patience: 35
  momentum: 0.9
  nepochs: 65
  wd: 0.0004
model_name: model11.ckpt
nesterov: true
network_args:
  graph: CTRGCN.graph.ntu_rgb_d.Graph
  graph_args:
    graph: nt
    labeling_mode: spatial
    num_node: 19
  num_class: 20
  num_person: 2
  num_point: 19
num_heads: 11
test_batch_size: 64
test_data_args:
  bone: false
  p_interval:
  - 0.95
  vel: false
  window_size: 64
train_data_args:
  bone: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  vel: false
  window_size: 64
